# Generated by Django 4.2.3 on 2023-07-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Room',
        ),
    ]
