# Generated by Django 4.2.3 on 2023-07-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_song',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
